language: python
python:
- '2.7'
- pypy
- pypy-5.3.1
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y zlib1g-dev libjpeg-dev python-dev
install:
- python setup.py install
script: python setup.py test
deploy:
  provider: pypi
  user: foxey
  password:
    secure: "oFhdV2MBUh5jeMKS++60yNoCbie20FtJ0JIlNU6tnPUf+AnoVRt1L7tSeLyATlkagv66Qte91WIR8iBPY2tJhXEz+nmnW5CCdyM5eAJgpoqlb35kAzxBfKwk3wJRG6nYJcL6iZNwFN3xOwIsPw3O8/iBWrPbyk7QIz7XdBivFNQP0I5HVwEW3HNyXLPVvYbA0e7DTIrmfS1vOp2sVQwoftnofZiZE99WLDq6UeGPO+aOvncB9k8D8tcB4niWXkQVD6NuwFgdFCFZNL9JU+xAjaW0V4CZ4S4KFj+1Zj+7DcWeRfOaAQtH7uSm4nL599xdpjc41IlZWEMyjVdXIVmz9LdeFYPF8FUxvm3Etu83/+e1Kc6aN0hcj5t2JDrjQwW7okItUD9y9/1uYol9OOmkdwxzNrXC9Dynx4hZsnHNMSUyV4CswRhsCd8jlzq6MBoMRFaKckenMkIBlZ+Q9BgJIw8i00DxEHohdhKA3u5EvYL/A+98pYNuU3cOarhOOg2AyLX8G1+SlBjD96sNQ2p42upbEKoO3I8BYZ3kFwiFoSxMYtyG7lJ9GVBjb/0bEGpoeBWTE3hVMS+iX/9R2k1f8nNJsxufl9DJVl1BrQFDArjcQl76NSpgqqq+MbSbW6Xf+iyClz82ZK7+hLhHKEFUJYyw21k5RT3/tSR6NOIY/SY="
  distributions: sdist bdist_wheel
  repo: foxey/volumio-buddy
  on:
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
