language: python
python:
  - "2.7"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"
# installing dependencies for Pillow
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y zlib1g-dev libjpeg-dev python-dev
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: python setup.py test
